name: activation service lint and test

defaults:
  run:
    working-directory: activation-service

on:
  push:
    paths:
      - activation-service/**
  workflow_dispatch:

jobs:
  Explore-Package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install GO
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 3m --verbose
          working-directory: activation-service

      - name: staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"
          working-directory: activation-service
        env:
          GO111MODULE: on

      - name: gofmt
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-flags: "-l -d"

      - name: Get dependencies
        run: |
          go mod download

      - name: Test
        run: go test -v ./...
