name: proxy Build and lint the source code

on:
  push:
    paths:
      - grid-proxy/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: grid-proxy
    steps:
      - uses: actions/checkout@v3.5.1

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Build
        run: |
          export PATH=/home/runner/go/bin:$PATH
          export GIT_COMMIT=$(git rev-list -1 HEAD) 
          go build -ldflags "-X main.GitCommit=$GIT_COMMIT" cmds/proxy_server/main.go
        env:
          GO111MODULE: on

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: grid-proxy

      - name: Test version
        run: ./main -v
