name: monbot lint

defaults:
  run:
    working-directory: monitoring-bot

on:
  push:
    paths:
      - monitoring-bot/**
  workflow_dispatch:

jobs:
  Explore-Package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3.5.0

      - name: Install GO
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 3m --verbose
          working-directory: monitoring-bot

      - name: staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"
          working-directory: monitoring-bot
        env:
          GO111MODULE: on

      - name: gofmt
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-flags: "-l -d"
