name: create and publish Docker images

# on:
#   workflow_dispatch:
#   release:
#     types: [published]

# NOTE: workflows using GITHUB_TOKEN doesn't get triggered after publishing release
# https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
# Thats why we will trigger this workflow after the main release workflow is completed

on:
  workflow_run:
    workflows: [Release]
    types: [completed]
  workflow_dispatch:

jobs:
  push-docker-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - dir: "activation-service"
            image: "tfactivation"
          - dir: "farmerbot"
            image: "tffarmerbot"
          - dir: "grid-proxy"
            image: "tfgridproxy"

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Checkout latest release tag
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout $LATEST_TAG

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/threefoldtech/${{ matrix.image }}
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.dir }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          #  For workflows triggered by release, `github.ref_name` is the short name for the release tag created.
          build-args: |
            version=${{ github.ref_name	 }}

      # - name: Push flist to grid hub
      #   uses: fjogeleit/http-request-action@v1
      #   with:
      #     url: https://hub.grid.tf/api/flist/me/docker
      #     method: "POST"
      #     bearerToken: ${{ secrets.HUB_TOKEN }}
      #     customHeaders: '{"Content-Type": "application/json"}'
      #     data: '{"image": "ghcr.io/threefoldtech/${{ matrix.image }}"}'
