# This GitHub action runs your tests for each commit push and/or PR. Optionally
# you can turn it on using a cron schedule for regular testing.
#
name: RMB lint and test

on:
  push:
    paths:
      - rmb-sdk-go/**
  workflow_dispatch:

defaults:
  run:
    working-directory: rmb-sdk-go

jobs:
  lint_and_test:
    name: lint and test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3.3.0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 3m --verbose
          working-directory: rmb-sdk-go

      - name: gofmt
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-flags: "-l -d"

      - name: Get dependencies
        run: |
          go mod download

      - name: run unit tests
        timeout-minutes: 10
        run: |
          go test -v ./...
