name: SDK Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: cd ${{ matrix.dir }} && go mod download

      - name: Test
        env:
          MNEMONICS: ${{ secrets.MNEMONICS }}
          NETWORK: dev
        run: cd ${{ matrix.dir }} && go test -v `go list ./... | grep -v integration_tests`

    strategy:
      fail-fast: true
      matrix:
        dir:
          - activation-service
          - grid-cli
          - grid-client
          - gridify
          - monitoring-bot
          - rmb-sdk-go